### PR TITLE
Remove the patch to hide the thinking banner - the banner itself was removed in CC 2.0.70

### LINKED ISSUE #296: Thinking patches are broken
```
Applying saved customizations to Claude Code...
Configuration saved at: /home/user/.config/tweakcc/config.json
Found Claude Code at: /home/user/n/lib/node_modules/@anthropic-ai/claude-code/cli.js
Version: 2.0.70
Loading system prompts...
Applying customizations...
patch: thinker format: failed to find formatMatch
patch: thinkingVisibility: failed to find banner function pattern
Customizations applied successfully!
```

### PR DESCRIPTION
**Pull request by basekevin**
Closes #296

### CODE REVIEW

File: src/patches/thinkingVisibility.ts [hunk 1]
```diff
@@ -3,47 +3,21 @@
...
 ): LocationResult | null => {
   // In this code:
   // ```
   // case "thinking":
-  //   if (!V)
-  //     return null;
-  //   return C3.createElement(UTQ, { addMargin: B, param: A, isTranscriptMode: V });`
+  //  if (!H && !G)
+  //    return null;
+  //  return b5.createElement(mn2, {addMargin: Q, param: A, isTranscriptMode: H,verbose: G });
```
Comment (bl-ue) [inline src/patches/thinkingVisibility.ts]:
```suggestion
  //  return b5.createElement(mn2, {addMargin: Q, param: A, isTranscriptMode: H, verbose: G });
```
