### PR TITLE
Fix `$` variable name replacement in system prompts

### LINKED ISSUE #237: Claude Code 2.0.55 unusable with tweakcc 3.1.3
I already tried https://github.com/Piebald-AI/tweakcc#troubleshooting. 

Image

Anytime I type anything when the tweakcc patches are applied, I am interrupted for some reason. I don't know why.

So then I restore the original Claude Code (preserves config.json) option from tweakcc, and everything works normally. 

Image

This was working fine for 2.0.54, which is why I believe it might a regression.

### PR DESCRIPTION
**Pull request by signadou**
Closes #237

### CODE REVIEW

File: src/utils/patches/systemPrompts.ts [hunk 1]
```diff
@@ -143,7 +143,8 @@ export const applySystemPrompts = async (
       const matchLength = match[0].length;
 
       // Replace the matched content with the interpolated content from the markdown file
-      content = content.replace(pattern, interpolatedContent);
+      // Use a replacer function to avoid special replacement pattern interpretation (e.g., $$ -> $)
```
Comment (bl-ue) [inline src/utils/patches/systemPrompts.ts]:
```suggestion
      // Use a replacer function to avoid special replacement pattern interpretation (e.g., $$ -> $), see #237
```

File: src/utils/promptSync.ts [hunk 2]
```diff
@@ -1272,7 +1272,8 @@ const applyIdentifierMapping = (
 
   for (const [humanName, actualVar] of sortedEntries) {
     const pattern = new RegExp(`\\b${humanName}\\b`, 'g');
-    result = result.replace(pattern, actualVar);
+    // Use a replacer function to avoid special replacement pattern interpretation (e.g., $$ -> $)
```
Comment (bl-ue) [inline src/utils/promptSync.ts]:
```suggestion
    // Use a replacer function to avoid special replacement pattern interpretation (e.g., $$ -> $), see #237
```
Need to fix this duplication some time.

**Review by bl-ue — CHANGES_REQUESTED** [review]
